package main

import (
	"encoding/json"
	"os"

	"github.com/shyandsy/shygoctl/api/spec"
	"github.com/shyandsy/shygoctl_gozero/gen"
	"github.com/zeromicro/go-zero/core/logx"
)

func main() {
	if len(os.Args) != 4 {
		panic("missing argument: filename of api specification generated by shygoctl")
	}

	filename := os.Args[1]
	dir := os.Args[2]
	style := os.Args[3]

	bytes, err := os.ReadFile(filename)
	if err != nil {
		panic(err)
	}

	api := &spec.ApiSpec{}
	if err := json.Unmarshal(bytes, api); err != nil {
		panic(err)
	}

	if err := gen.DoGenProject(api, dir, style); err != nil {
		logx.Error("DoGenProject failed", "err", err)
	}
}
